POST http://localhost:4000/api/tickets HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjcyOTRkYWJmZjc3ZGUzN2EwZWU5MDkiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxODc4NTM0OSwiZXhwIjoxNzE4Nzg4OTQ5fQ.LcNF6L0nUHN1qf857YC3Zgm_n3a3iHHaDVQpoo9De0E

{
  "user": "282d29ee-de97-4814-bf70-7ffeabd991ab",
  "title": "Ticket #18",
  "description": "This is a new ticket description"
}
